import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#244855",
          foreground: "#FBE9D0",
          50: "#e8eff1",
          100: "#c5d8dc",
          200: "#9fbfc5",
          300: "#79a5ae",
          400: "#5e919b",
          500: "#437e88",
          600: "#3a6e77",
          700: "#2e5a63",
          800: "#244855",
          900: "#152c35",
        },
        accent: {
          DEFAULT: "#E64833",
          foreground: "#ffffff",
          50: "#fdecea",
          100: "#fac8c3",
          200: "#f7a09a",
          300: "#f37870",
          400: "#f05a4d",
          500: "#E64833",
          600: "#cc3d29",
          700: "#a8301f",
          800: "#852316",
          900: "#61180e",
        },
        secondary: {
          DEFAULT: "#874F41",
          foreground: "#FBE9D0",
          50: "#f4ece9",
          100: "#e0cdc8",
          200: "#caaba4",
          300: "#b48980",
          400: "#a46f63",
          500: "#935646",
          600: "#874F41",
          700: "#6f3f33",
          800: "#572f26",
          900: "#3e1f18",
        },
        soft: {
          DEFAULT: "#90AEAD",
          50: "#f0f4f4",
          100: "#d8e4e3",
          200: "#bed2d1",
          300: "#a3bfbe",
          400: "#90AEAD",
          500: "#7d9d9c",
          600: "#6a8a89",
          700: "#547170",
          800: "#3e5756",
          900: "#293d3c",
        },
        cream: {
          DEFAULT: "#FBE9D0",
          50: "#fef9f3",
          100: "#fdf2e3",
          200: "#FBE9D0",
          300: "#f8d9b3",
          400: "#f4c891",
          500: "#efb66e",
          600: "#e8a04a",
          700: "#d4882b",
          800: "#b06d1e",
          900: "#8c5314",
        },
        force: {
          teal: "#244855",
          red: "#E64833",
          brown: "#874F41",
          muted: "#90AEAD",
          cream: "#FBE9D0",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-left": {
          from: { opacity: "0", transform: "translateX(-30px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "fade-in-right": {
          from: { opacity: "0", transform: "translateX(30px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(40px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "counter-up": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "pulse-dot": {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.5)", opacity: "0.7" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "shimmer": {
          from: { backgroundPosition: "-200% 0" },
          to: { backgroundPosition: "200% 0" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.6s ease-out forwards",
        "fade-in-left": "fade-in-left 0.6s ease-out forwards",
        "fade-in-right": "fade-in-right 0.6s ease-out forwards",
        "scale-in": "scale-in 0.5s ease-out forwards",
        "slide-up": "slide-up 0.7s ease-out forwards",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
        "shimmer": "shimmer 2s linear infinite",
        "spin-slow": "spin-slow 8s linear infinite",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "hero-gradient": "linear-gradient(135deg, #244855 0%, #1a3340 50%, #0d1f28 100%)",
        "card-gradient": "linear-gradient(135deg, rgba(36,72,85,0.95) 0%, rgba(36,72,85,0.8) 100%)",
        "shimmer-gradient": "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.1) 50%, transparent 100%)",
      },
      boxShadow: {
        "force": "0 4px 20px rgba(36,72,85,0.15)",
        "force-lg": "0 8px 40px rgba(36,72,85,0.2)",
        "accent": "0 4px 20px rgba(230,72,51,0.3)",
        "card": "0 2px 15px rgba(0,0,0,0.08)",
        "card-hover": "0 8px 30px rgba(0,0,0,0.15)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
